# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Smooth"
license = "MIT"
licenselink = "https://github.com/simoatze/smooth/blob/master/LICENSE.md"
description = "A simple template for HUGO websites"
homepage = "https://github.com/simoatze/smooth/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Simone Atzeni"
  homepage = "http://www.simoneatzeni.net"
